google/cloud/sql/connector/connector.py
Adding the `get_metadata` function into `connector.py`.
FYI: @kurtisvg, @jkwlui
=> Adding get_metadata function

.gitignore
I forgot to take out `new-docker.sh` from the `.gitignore`.
=> Removed an extra line in the .gitignore.

.flake8, google/cloud/sql/connector/InstanceConnectionManager.py, requirements.txt, tests/test_instanceconnectionmanager_unit.py
The purpose of this PR is to convert _get_metadata and _get_ephemeral to asynchronous functions.
FYI: @kurtisvg, @jkwlui
=> Converting _get_metadata and _get_ephemeral to asynchronous functions

README.md, google/cloud/sql/connector/InstanceConnectionManager.py, google/cloud/sql/connector/connector.py, tests/test_instanceconnectionmanager_unit.py
Re-working the connect method to return a DB-API connection object rather than an OpenSSL connection.
=> Added connect method

google/cloud/sql/connector/connector.py
Fixes https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/issues/26
=> fix: avoid hang on connector.connect

google/cloud/sql/connector/InstanceConnectionManager.py
Adds a header for estimating version usage. 
Waiting to replace "header-value-here" before merging.
=> chore: Add version header.

.gitignore, google/cloud/sql/connector/InstanceConnectionManager.py, tests/system/test_pg8000_connection.py
updating an outdated docstring
=> chore: update docstring in InstanceConnectionManager 

requirements.txt
There was a new release 2 days ago that includes the changes we made 🎉
=> chore: update pg8000 version to 1.18.0

google/cloud/sql/connector/connector.py
=> feat: reuse instance connection managers

google/cloud/sql/connector/InstanceConnectionManager.py, google/cloud/sql/connector/connector.py, google/cloud/sql/connector/utils.py, tests/unit/test_instanceconnectionmanager.py, tests/unit/test_utils.py
=> fix: generate keys asynchronously

.mypy.ini, google/cloud/sql/connector/instance_connection_manager.py, requirements-test.txt, requirements.txt, setup.py, tests/system/test_pytds_connection.py
Add support for [pytds](https://github.com/denisenkom/pytds/) driver
DO NOT MERGE until:
=> feat: add pytds support

.kokoro/python3.7/windows/common.cfg, .kokoro/python3.7/windows/continuous.cfg, .kokoro/python3.7/windows/periodic.cfg, .kokoro/python3.7/windows/presubmit.cfg, .kokoro/tests/run_tests.bat, .kokoro/tests/run_tests_windows.sh
=> chore(ci): run tests on Windows

google/cloud/sql/connector/version.py
=> chore: update version to v0.2.1-dev

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/documentation-issue.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/question.md
=> chore: add issue templates

google/cloud/sql/connector/refresh_utils.py
=> chore: move rstrip() to where proxy extracts token

google/cloud/sql/connector/instance_connection_manager.py
=> fix: only replace refresh result if successful or current is invalid

google/cloud/sql/connector/connector.py, google/cloud/sql/connector/instance_connection_manager.py, google/cloud/sql/connector/rate_limiter.py, tests/unit/test_instance_connection_manager.py, tests/unit/test_rate_limiter.py
fixes #136 
Let me know if I should add more comments explaining the rate limiter implementation.
=> feat: add rate limiter and force refresh function

README.md, setup.py
=> feat: switch development status to beta

README.md, google/cloud/sql/connector/version.py
=> docs: update README with connection pooling

README.md, google/cloud/sql/connector/connector.py, tests/system/test_ip_types.py
Wait until right before next release to merge. That way README and Pypi package will be consistent with eachother.
=> fix!: consolidate to 'ip_type' instead of 'ip_types' for connect args

README.md
Include links to instructions about installing the gcloud SDK.
=> chore: update README.md to provide SDK install instructions

.kokoro/release.sh, .kokoro/release/common.cfg
=> build: switch to keystore for publication

google/cloud/sql/connector/instance_connection_manager.py, google/cloud/sql/connector/rate_limiter.py, tests/conftest.py, tests/system/test_connector_object.py, tests/unit/test_instance_connection_manager.py, tests/unit/test_rate_limiter.py
@shubha-rajan Would love to have you take a glance at this when you have a free second :)
=> fix: make asyncio.Lock() run in background thread

google/cloud/sql/connector/__init__.py, google/cloud/sql/connector/connector.py, google/cloud/sql/connector/instance_connection_manager.py, google/cloud/sql/connector/refresh_utils.py, tests/unit/test_refresh_utils.py
=> fix!: update error messages and doc strings

google/cloud/sql/connector/connector.py, google/cloud/sql/connector/instance_connection_manager.py, tests/unit/test_connector.py, tests/unit/test_rate_limiter.py
=> chore: improve task and test cleanup

noxfile.py
Updating because of new bug: https://github.com/psf/black/issues/2964
=> chore(deps): update dependency black to 22.3.0

google/cloud/sql/connector/connector.py, google/cloud/sql/connector/instance_connection_manager.py, google/cloud/sql/connector/pg8000.py, google/cloud/sql/connector/pymysql.py, google/cloud/sql/connector/pytds.py, google/cloud/sql/connector/utils.py, tests/unit/test_connector.py
=> chore: refactor connect into connect_info

README.md
=> chore: update install instructions per driver

google/cloud/sql/connector/pg8000.py
Adding comment for extra detail as to how pg8000 connection works.
=> chore: add comment for pg8000 connection

tests/system/test_connector_object.py, tests/system/test_ip_types.py, tests/system/test_pg8000_connection.py, tests/system/test_pg8000_iam_auth.py, tests/system/test_pymysql_connection.py, tests/system/test_pytds_connection.py
Updating samples in pages such as [Connecting with Connectors](https://cloud.google.com/sql/docs/mysql/connect-connectors#python_1) to show imports as well as a have a few more comments.
=> chore: update region tags in test samples

google/cloud/sql/connector/instance.py
Prefer TLSv1.3 and warn users if falling back to TLS v1.2
fixes #418
=> chore: prefer TLSv1.3 for all connections

README.md
Updating header image to use absolute raw path so that it can be rendered in [Cloud SQL Python Connector pypi page](https://pypi.org/project/cloud-sql-python-connector/)
=> chore: update README image to absolute path

README.md
Update usage sample of `asyncpg` with:
- `asyncio.run(main())` for running script
-  Syntax error of the `for row in results:` iteration
=> chore: update README samples for async driver usage

google/cloud/sql/connector/connector.py
Missed a re-raise as part of #482
=> chore: remove re-raise from stacktrace

requirements-test.txt, setup.py
Bumping the version to fix #548
=> chore: bump pg8000 version to 1.29.4

.github/workflows/tests.yml, noxfile.py, setup.py
Adding test coverage and support for Python  3.11
Closes #545
=> feat: add support for Python 3.11

samples/notebooks/mysql_python_connector.ipynb, samples/notebooks/postgres_python_connector.ipynb, samples/notebooks/sqlserver_python_connector.ipynb
Updating notebook samples to use sandwiches 🥪  database instead of movies 🎥.
Also updating sqlalchemy to v2 in notebooks.
=> chore: update sample used in notebooks

google/cloud/sql/connector/version.py
=> chore: bump to next dev version

samples/notebooks/sqlserver_python_connector.ipynb
Updating private IP sample in SQL Server notebook
=> chore: update SQL Server notebook

SECURITY.md
Adding security file to match other client libs: https://github.com/googleapis/python-bigquery/blob/main/SECURITY.md
=> chore: add security policy file SECURITY.md

.github/workflows/scorecard.yml
Adding code scanning with OSSF scorecards: https://github.com/ossf/scorecard-action/
=> chore(ci): add OSSF scorecard action

.kokoro/requirements.txt
Update requests for kokoro release job
Closes #734
=> chore: update kokoro requirements.txt

README.md
Updating import so that it doesn't conflict with `engine` variable
=> chore: update sample in README

.github/blunderbuss.yml
Adding @enocom as assignee for issues on Cloud SQL Python while I am on PTO
=> chore: update blunderbuss.yml for issues

google/cloud/sql/connector/instance.py, tests/unit/mocks.py, tests/unit/test_instance.py
Make naming across languages with use of `ConnectionInfo`
Closes #877
=> chore: update naming of `InstanceMetadata` to `ConnectionInfo`

google/cloud/sql/connector/instance.py, tests/unit/test_instance.py
Domain-scoped project names (i.e. domain:project) were thought to be legacy but TPC universes will follow the pattern adding a TPC scoped prefix to projects. 
This PR adds support for instance connection names that include a domain-scoped project name.
(ex. google.com:my-project:my-region:my-instance) which would previously throw an error for invalid instance connection name.
=> feat: add support for domain-scoped projects

google/cloud/sql/connector/refresh_utils.py, tests/conftest.py, tests/unit/mocks.py, tests/unit/test_instance.py, tests/unit/test_refresh_utils.py
Previous fake credentials object was copy/pasted from random code somewhere.
Updating fake credentials to have more control, such as setting expiry etc.
Closes #901
=> chore: use better fake for credentials

google/cloud/sql/connector/connector.py
Update the `create_async_connector` args so they are consistent with the Connector.
=> fix: update create_async_connector args

.github/labels.yml
Incorrect label, missing whitespace
=> chore: Update labels.yml

tests/system/test_connector_object.py
No need to use logger in tests, in fact the `logging.exception` is not being used properly and causing stacktrace to hide true cause of error due to error `e` being converted into a string.
```
FAILED tests/system/test_connector_object.py::test_connector_with_credentials - TypeError: not all arguments converted during string formatting
```
Should use context manager to auto-close connector where possible.
=> chore: update system tests

.kokoro/release.sh, .kokoro/release/common.cfg
Update pypi release token keystore to new key.
=> ci: update keystore to newer key

.github/release-trigger.yml
=> build: use multiScm for Kokoro release builds

.ci/cloudbuild.yaml, .github/workflows/tests.yml, tests/system/test_pymysql_connection.py, tests/system/test_pymysql_iam_auth.py
Add integration tests for MySQL for Cloud SQL's [Managed Connection Pooling](https://cloud.google.com/sql/docs/mysql/managed-connection-pooling) (MCP)
=> test: add MySQL MCP tests

tests/system/test_pymysql_connection.py
Reverts GoogleCloudPlatform/cloud-sql-python-connector#1270
=> Revert "test: add broken test to test scheduled reporter"
