GoogleCloudPlatform/cloud-sql-python-connector

- google/cloud/sql/connector/connector.py
The purpose of this PR is to set a basic definition on what the `connect` method is supposed to do. Raises a `NotImplementedError` for now.
> Creating an interface for connect

- google/cloud/sql/connector/InstanceConnectionManager.py
The purpose of this PR is to make sure the public and private keys are generated when the `InstanceConnectionManager` is initialized.
> Added in generate_keys in the __init__ to prepare for _perform_refresh

- google/cloud/sql/connector/InstanceConnectionManager.py
This PR cleans up two small issues
1) a var was incorrectly named
2) the credentials creation was copying default credentials and specifying creds. This wasn't necessary as we can provide scopes when retrieving creds.
fixes #24
> fix: correct variable name and credential copying

- google/cloud/sql/connector/instance_connection_manager.py
- google/cloud/sql/connector/utils.py
fixes #22
Replaced the NamedTemporaryFiles with a TemporaryDirectory in which new files are created. When used in a context manager, a TemporaryDirectory and all its contents are deleted once the context is closed ([Python docs](https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory))
> fix: use temporary directory instead of tempfile for Windows compatibility

- requirements.txt
- setup.py
Version 1.11.0 of pydts was released earlier today so we don't have to pull from GitHub anymore.
> chore: upgrade pytds to latest release version

- .github/workflows/release-please.yml
- .kokoro/populate-secrets.sh
- .kokoro/release.sh
- .kokoro/release/common.cfg
- .kokoro/release/release.cfg
- .kokoro/trampoline.sh
- setup.cfg
The release job can be manually triggered from fusion or with a stubby call once a release PR is merged.  The Yoshi team uses autorelease to trigger new releases automatically when new tags are merged so we can probably do something similar in the future.
> chore: set up release-please workflow and kokoro release script

- .gitignore
- noxfile.py
> chore: add 'twine check dist/*' to lint

- google/__init__.py
- google/cloud/__init__.py
- google/cloud/sql/connector/__init__.py
- noxfile.py
mypy checks started failing in #113 - this fixes it
> chore: fix failing type checks

- tests/system/test_pg8000_connection.py
- tests/system/test_pymysql_connection.py
- tests/system/test_pytds_connection.py
Adding region tags to these code snippets so that we can include them in documentation. The proposed region tag pattern for connector samples is:
`cloud_sql_connector_{engine}_{driver}`
> chore: add region tags to connection code in tests

- google/cloud/sql/connector/refresh_utils.py
Strips trailing `.` characters from access tokens
fixes #137
> fix: strip padding from access tokens if present

- README.md
- google/cloud/sql/connector/instance_connection_manager.py
Add support for Integrated Security (Active Directory auth) for Windows using [SSPI](https://docs.microsoft.com/en-us/windows-server/security/windows-authentication/security-support-provider-interface-architecture). PyTDS offers experimental support for Kerberos auth on non-Windows platforms, but I haven't tested it yet, so for now only Windows will be supported.
> feat: support Active Directory auth for Windows

- google/cloud/sql/connector/instance_connection_manager.py
Noticed an error in the logs that said that the "warn" method was deprecated, and `logger.exception` is probably more appropriate here anyway.
> chore: update error message and replace deprecated logger.warn method

- google/cloud/sql/connector/instance_connection_manager.py
- noxfile.py
- tests/unit/test_instance_connection_manager.py
Refactored perform_refresh to await the result of refresh_task instead of using a callback (this makes testing simpler), and added tests to confirm that InstanceData replacement is working as expected.
> chore: refactor perform_refresh and add tests

- google/cloud/sql/connector/instance_connection_manager.py
- google/cloud/sql/connector/refresh_utils.py
- tests/unit/test_instance_connection_manager.py
- tests/unit/test_refresh_utils.py
Refactor refresh methods to match those of the [Cloud SQL Go Connector](https://github.com/GoogleCloudPlatform/cloud-sql-go-connector).
Separate PR will make refresh methods into static methods within `refresh_utils.py`
> chore: refactor refresh methods

- requirements.txt
Because we create aiohttp calls directly we are no longer using google-api-python-client
> chore: remove unused google-api-python-client

- README.md
- google/cloud/sql/connector/__init__.py
- google/cloud/sql/connector/connector.py
- tests/system/test_connector_object.py
> fix: resolve TimeoutError and add context manager to Connector

- google/cloud/sql/connector/__init__.py
- google/cloud/sql/connector/connector.py
- google/cloud/sql/connector/instance.py
- google/cloud/sql/connector/pytds.py
- tests/unit/test_connector.py
- tests/unit/test_instance.py
- tests/unit/test_refresh_utils.py
Renaming `InstanceConnectionManager` class to `Instance` as it no longer manages connections, that has been moved up a level to the connector.
> chore: update InstanceConnectionManager to Instance

- README.md
- google/cloud/sql/connector/connector.py
We want to now recommend to users to initialize a `Connector` object and not rely on the default `connect` method to do this for them. Will deprecate the default `connect` method in a future release.
> feat!: deprecate default connect method

- .github/renovate.json
- noxfile.py
- requirements-test.txt
- requirements.txt
Updating dependencies to be reachable by renovate-bot as well as removing driver dependencies from basic requirements.txt
> chore: allow renovate to configure all dependencies

- google/__init__.py
- google/cloud/__init__.py
- google/cloud/sql/connector/__init__.py
- requirements-test.txt
In `mypy==0.920` and beyond it is no longer required to type hint `__path__` as it defaults to the correct type.
> chore(deps): update mypy to 0.942

- .github/workflows/tests.yml
- .kokoro/python3.10/linux/common.cfg
- .kokoro/python3.7/linux/common.cfg
- .kokoro/python3.7/windows/common.cfg
- .kokoro/python3.8/linux/common.cfg
- .kokoro/python3.9/linux/common.cfg
Moving Python Connector unit tests from Kokoro to Github Actions. Additionally unit tests will now run on Mac builds.
> build: move unit tests to Github Actions

- setup.py
Replace `google-api-python-client` with `google-auth` in core deps.
> chore: update core dependencies to use google-auth

- tests/system/test_ip_types.py
- tests/system/test_pg8000_connection.py
- tests/system/test_pg8000_iam_auth.py
- tests/system/test_pymysql_connection.py
- tests/system/test_pytds_connection.py
Updating system tests to use `Connector` object over global `connector.connect` method which is deprecated and will be removed in future release.
> chore: update system tests to use Connector object

- requirements-test.txt
- tests/pytest.ini
Pytest now requires either `strict` or `auto` configuration to determine between pytest vs pytest-asyncio tests. 
Closes #401
> chore(deps): update dependency pytest-asyncio to 0.19.0

- .github/release-trigger.yml
Enabling `release-trigger` on repo, should allow the merging of release-please PRs to kick off Kokoro release job, removing the manual step of the release process
> chore: enable release-trigger for one click releases

- google/cloud/sql/connector/connector.py
- tests/unit/test_connector.py
Background threads used for `Connector()` are daemon threads and by default do not get killed until process exits. Since we are spinning up these threads with `loop.run_forever` the thread will not get killed until the event loop is closed. Which in the current state is when the Python program exits, which is not efficient for long running programs.
To fix this, we should call `loop.stop` when closing a `Connector` object which will in turn kill the background daemon thread.
Closes #409
> fix: stop event loop on Connector.close

- google/cloud/sql/connector/instance.py
- requirements.txt
- setup.py
The [`pyopenssl`](https://pypi.org/project/pyOpenSSL/) library recommends using the [`pyca/cryptography`](https://github.com/pyca/cryptography) library over its internal [crypto](https://www.pyopenssl.org/en/stable/api/crypto.html) module.
Note from the pyopenssl docs:
> Note: The Python Cryptographic Authority strongly suggests the use of [pyca/cryptography](https://github.com/pyca/cryptography) where possible. If you are using pyOpenSSL for anything other than making a TLS connection you should move to cryptography and drop your pyOpenSSL dependency.
We already have the `crypotgraphy` library as a core dependency, so we can consolidate usage to it and drop `pyopenssl`.
> chore: drop pyopenssl core dependency

- .flake8
- requirements-test.txt
In newer versions of `flake8-annotations` a new opinionated check `ANN401` was added that should be disabled by default to allow `typing.Any` type hints.
Closes #363
> chore: update dependency flake8-annotations to 2.9.1

- google/cloud/sql/connector/connector.py
As part of #220 , we switched the connector argument `ip_types` to `ip_type` to better reflect the argument and meaning.
Removing the old `ip_types` option as it has been deprecated for several months now.
> chore: remove deprecated `ip_types` argument

- README.md
Linking header image to [Python Connector blog](https://cloud.google.com/blog/topics/developers-practitioners/how-connect-cloud-sql-using-python-easy-way)
[Test it here](https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/tree/update-readme)
> chore: link README image to blog post

- .github/flakybot.yaml
- .github/workflows/tests.yml
- noxfile.py
- tests/system/test_ip_types.py
Enabling Flakybot to create issues with `p2` label for tests that fail during `schedule` (periodic) or `push` (continuous) builds.
Example issue opened by FlakyBot: #448
> chore(ci): enable Flakybot on tests

- noxfile.py
`py.test` is the old invocation of pytests. The newer version is `pytest` and `py.test` will most likely be [deprecated in the future](https://stackoverflow.com/questions/39495429/py-test-vs-pytest-command).
> chore: update py.test to pytest

- google/cloud/sql/connector/connector.py
- google/cloud/sql/connector/instance.py
Allow configuration of quota project for Cloud SQL Admin API calls by adding header field for [`x-goog-user-project`](https://cloud.google.com/storage/docs/xml-api/reference-headers#xgooguserproject)
Closes #469
> feat: add quota_project arg to specify quota and billing project

- google/cloud/sql/connector/connector.py
- google/cloud/sql/connector/instance.py
- google/cloud/sql/connector/refresh_utils.py
- tests/unit/test_refresh_utils.py
Adding `sqladmin_api_endpoint` arg to `Connector` to allow specifying different Cloud SQL Admin API base URL endpoint. This feature is meant to be used in development environments.
Closes #468
> feat: add `sqladmin_api_endpoint` arg to specify Cloud SQL Admin API endpoint

- google/cloud/sql/connector/refresh_utils.py
`aiohttp` has a built-in function to return the response in JSON format. There is no need to return using `text()` and then convert to JSON.
> chore: return aiohttp response as JSON

- google/cloud/sql/connector/instance.py
Re-raising an error through `raise e` adds the re-raise to the stracktrace while just using `raise` will preserve the stacktrace as is.
`raise e` stacktrace:
```
File "/usr/local/google/home/jackwoth/.pyenv/versions/3.10.1/lib/python3.10/site-packages/google/cloud/sql/connector/refresh_utils.py", line 224, in _is_valid
metadata = await task
File "/usr/local/google/home/jackwoth/.pyenv/versions/3.10.1/lib/python3.10/site-packages/google/cloud/sql/connector/connector.py", line 245, in get_connection
instance_data, ip_address = await instance.connect_info(ip_type)
File "/usr/local/google/home/jackwoth/.pyenv/versions/3.10.1/lib/python3.10/site-packages/google/cloud/sql/connector/instance.py", line 512, in connect_info
instance_data = await self._current
File …
```
> chore: remove re-raised exceptions from stacktrace

- google/cloud/sql/connector/connector.py
- google/cloud/sql/connector/exceptions.py
- google/cloud/sql/connector/instance.py
- google/cloud/sql/connector/pytds.py
- tests/unit/test_connector.py
- tests/unit/test_instance.py
- tests/unit/test_pytds.py
Moving all custom exceptions to `exceptions.py` to keep main files focused on application code.
> chore: move custom exceptions to exceptions.py

- google/cloud/sql/connector/instance.py
- google/cloud/sql/connector/refresh_utils.py
- tests/conftest.py
- tests/unit/test_instance.py
- tests/unit/test_refresh_utils.py
Down-scope credentials and OAuth2 token used in `generateEphemeral` API request for IAM AuthN to have only `"https://www.googleapis.com/auth/sqlservice.login"` scope.
Closes #486
> feat: downscope token used for IAM DB AuthN

- setup.py
Adding constraint on [`cryptography`](https://cryptography.io/en/latest/) dependency due to vulnerability found in OpenSSL.
Cryptography 38.0.3 release notes: 
> Updated Windows, macOS, and Linux wheels to be compiled with OpenSSL 3.0.7, which resolves CVE-2022-3602 and CVE-2022-3786.
> fix: set minimum version constraint on cryptography

- google/cloud/sql/connector/instance.py
In Python 3.10, `ssl.PROTOCOL_TLS` is deprecated and outputs warnings in logs/tests:
```
DeprecationWarning: ssl.PROTOCOL_TLS is deprecated
self.context = ssl.SSLContext(ssl.PROTOCOL_TLS)
```
Instead, one of [`ssl.PROTOCOL_TLS_CLIENT`](https://docs.python.org/3/library/ssl.html#ssl.PROTOCOL_TLS_CLIENT) or [`ssl.PROTOCOL_TLS_SERVER`](https://docs.python.org/3/library/ssl.html#ssl.PROTOCOL_TLS_SERVER) should be used, in our case CLIENT.
However, `ssl.PROTOCOL_TLS_CLIENT` brings with it some [new changes](https://docs.python.org/3/library/ssl.html#ssl.PROTOCOL_TLS_CLIENT). It sets `check_hostname` to True and `verify_mode` to `CERT_REQUIRED` by default. (`PROTOCOL_TLS` defaulted these values to False and CERT_NONE)
These new defaults lead to an error when using the TLS connection:
``` …
```
> fix: update TLS protocol for python3.10

- google/cloud/sql/connector/refresh_utils.py
- tests/unit/mocks.py
Consolidating string formatting to f-strings as they are more efficient than `.format()`
> chore: consolidate string formatting to f-strings

- google/cloud/sql/connector/instance.py
- google/cloud/sql/connector/utils.py
- tests/conftest.py
- tests/unit/test_instance.py
- tests/unit/test_utils.py
The `_auth_init` method to initialize credentials does not need to be an `Instance` class method. It does not rely on any class attributes and thus can me moved to the`utils.py` file as a utility method.
> chore: move `_auth_init` out of Instance class

- google/cloud/sql/connector/instance.py
- google/cloud/sql/connector/refresh_utils.py
- tests/unit/test_refresh_utils.py
Making refresh calculation more reliable and the same when connecting using both auto IAM AuthN or regular built-in database users.
> feat: improve reliability of certificate refresh

- google/cloud/sql/connector/instance.py
- google/cloud/sql/connector/refresh_utils.py
- tests/unit/test_refresh_utils.py
Adding validation to check that instance connection name region matches that of actual Cloud SQL instance.
> chore: validate region matches instance

- README.md
- requirements-test.txt
- tests/system/test_connector_object.py
- tests/system/test_ip_types.py
- tests/system/test_pg8000_connection.py
- tests/system/test_pg8000_iam_auth.py
- tests/system/test_pymysql_connection.py
- tests/system/test_pymysql_iam_auth.py
- tests/system/test_pytds_connection.py
SQLAlchemy major version release v2 has been released. With it comes a few new changes: 
- no raw strings can be executed, instead the use of `sqlalchemy.text()` must be used to prepare queries. This helps limit the ability for SQL injection attacks.
- Autocommit is turned off by default to reduce sub-transaction issues
Closes #596
> chore(deps): update sqlalchemy to v2

- samples/notebooks/sqlserver_python_connector.ipynb
Reverts GoogleCloudPlatform/cloud-sql-python-connector#621
It turns out that when creating a SQLAlchemy connection pool for pytds it requires a `host` value in the URI
```python
pool = sqlalchemy.create_engine(
"mssql+pytds://<HOST>",
creator=getconn,
)
``` 
It does not actually matter what this host field's value is as the Python Connector's `getconn` that is used as the `creator` to make the connections does not take into account when connecting.
Reverting a change that made it seem like this value had to be the Private IP address of the Cloud SQL instance as it in fact does not.
> chore: Revert "chore: update SQL Server notebook"

- samples/notebooks/sqlserver_python_connector.ipynb
- tests/system/test_pytds_connection.py
The latest version v0.3.5 of [sqlalchemy-pytds](https://pypi.org/project/sqlalchemy-pytds/) has fixed an issue where the `host` param in SQLAlchemy URL had to be set, it is now optional. This simplifies the samples for connecting using the Python Connector as we no longer need the placeholder `host` value of localhost in our SQLAlchemy URLs.
> chore: remove `host` param from SQL Server samples

- .github/workflows/scorecard.yml
Turns out you can't use the shorthand for the scorecard-action for some reason.
> chore(ci): fix scorecard action version

- .github/renovate.json
- .github/workflows/coverage.yml
- .github/workflows/labels.yaml
- .github/workflows/lint.yml
- .github/workflows/scorecard.yml
- .github/workflows/tests.yml
An OSSF security best practice is to pin Github Action versions to their SHA digests.
Renovate supports this feature: https://docs.renovatebot.com/modules/manager/github-actions/#additional-information
> chore(ci): pin Github Actions to SHA digests

- .github/workflows/scorecard.yml
Filtering out `DangerousWorkflow` alerts as they do not take into account the proper use of the `tests: run` label.
Native ability to only run selected checks should be coming soon as part of: https://github.com/ossf/scorecard-action/issues/1107
> ci: update scorecard to skip false positive

- .github/workflows/scorecard.yml
Until `scorecard-action` natively supports disabling certain checks, we must remove publishing of results so that we can filter out false positives.
Reason for this is that if you are publishing results, no custom steps can be added to workflow: https://github.com/ossf/scorecard-action/blob/main/README.md?plain=1#L21
> ci: update scorecard to not publish results

- .github/workflows/coverage.yml
- .github/workflows/lint.yml
- .github/workflows/tests.yml
Making workflow default permissions `read-all` stopped the ability for Github Action to remove the `tests: run` label from PRs. In order to successfully remove the label, the action needs write access to issues and pull requests.
> ci: add permissions for label to be removed

- .kokoro/release/release.cfg
The release job will now build the package artifacts `dist/*.tar.gz` and `dist/*.whl` and report it to Kokoro 
using define_artifacts so that Kokoro can generate an SBOM for this artifact.
> ci: Track released artifacts for EO 14028 compliance.

- tests/conftest.py
Gracefully close event loop fixture used in tests.
Closes #694 which was caused due to event loop fixture not cleaning up properly and not being able to close event loop.
> chore: update test fixture

- google/cloud/sql/connector/connector.py
- google/cloud/sql/connector/instance.py
- google/cloud/sql/connector/refresh_utils.py
Adding `if TYPE_CHECKING:` to improve runtime efficiency. `TYPE_CHECKING` is False at runtime, allowing imports  that are only used for type hints etc. to only be imported by 3rd party static type checkers (aka lint job etc).
See [Python official docs](https://docs.python.org/3/library/typing.html#typing.TYPE_CHECKING) for more details.
> chore: add TYPE_CHECKING for imports

- google/cloud/sql/connector/connector.py
- google/cloud/sql/connector/pymysql.py
- tests/unit/test_connector.py
- tests/unit/test_pymysql.py
Allow database drivers to handle timeout instead of Connector itself.
Closes #759
> fix: improve timeout handling

- README.md
- google/cloud/sql/connector/connector.py
- google/cloud/sql/connector/exceptions.py
- google/cloud/sql/connector/instance.py
- google/cloud/sql/connector/refresh_utils.py
- tests/unit/mocks.py
- tests/unit/test_instance.py
Add a new IP type `IPTypes.PSC` to support connections to Cloud SQL using [private service connect](https://cloud.google.com/vpc/docs/private-service-connect).
> feat: add support for PSC connections

- .kokoro/requirements.txt
Closes #799 as this is duplicate since dependabot doesn't have access to secrets in test builds.
> chore: bump pygments to 2.15.0 in .kokoro

- setup.py
The library is fully typed, so add a marker to allow linters like mypy to pick this up as specified in PEP561.
> chore: add py.typed marker

- .github/workflows/tests.yml
Run unit tests on Linux only, integration tests cover all OSs
> ci: pare down unit tests

- google/cloud/sql/connector/refresh_utils.py
- tests/unit/mocks.py
- tests/unit/test_refresh_utils.py
Access token and ephemeral cert expiration time should be in UTC  and `_seconds_until_refresh` method compares it with local time which is incorrect.
It does not provide obviously incorrect results if you are west of GMT (i.e. your time zone is UTC-N). In such a case, "expiration - localtime" is a large positive number.
But my (workload) time zone is UTC+1 and `(expiration - datetime.datetime.now()).total_seconds())` returns negative number (expiration is `min(ephemeral_cert.expiration, credentials.expiration)`). Resulting in `return 0` , thus `Instance` schedules next refresh instantly. Well, it won't be run instantly because of rate-limiter set to 1/30.
Here is my test snippet with logs, note that `_perform_refresh` logs appear every 30 seconds. Note that I'm running this in UTC+1 time …
> fix: Use utcnow() in refresh calculation

- tests/conftest.py
- tests/unit/test_instance.py
- tests/unit/test_rate_limiter.py
Dynamically find event loop over using event_loop fixture. Using event_loop as a fixture is being deprecated
Closes #888
> chore: remove `event_loop` fixture

- google/cloud/sql/connector/instance.py
- google/cloud/sql/connector/refresh_utils.py
- tests/unit/test_instance.py
- tests/unit/test_refresh_utils.py
Alternative to #894 
There are two credential objects managed in the Python Connector. 
1) Credential object used for authenticating the SQL Admin API calls
2) Credential object used for automatic IAM authentication that has login scopes and is embedded into the ephemeral cert to be later used as the "password" for an IAM login
When automatic IAM authentication is used, the expiration of the ephemeral cert and the IAM credentials object OAuth2 token should be compared when calculating the time until the next refresh operation occurs. This is because the cert and the OAuth2 token must both be valid in order for the successful connection.
Previously we were incorrectly using the expiry of credentials object for the SQL Admin APIs to calculate the next refresh when using IAM authentication. …
> fix: use IAM login creds in expiration logic

- setup.py
Driver packages like `asyncpg` have corresponding stub libraries such as [asyncpg-stubs](https://pypi.org/project/asyncpg-stubs/) that are aggressive on forcing latest version of driver for typing. Driver versions in the Connector may be slightly out of sync as we wait for next release at our monthly cadence. Being more lenient in driver version and not forcing the version to be explicit will allow users to not run into version conflicts between connector `asyncpg` driver version and stub library `asyncpg` version.
cc @kurtisvg
> chore: make driver versions more flexible

- .github/renovate.json
For some reason #938 did update `setup.py` as it normally does.
This change explicitly adds setup.py to renovate's config, not relying on defaults.
> chore: explicitly add `pip_setup` to renovate.json

- requirements-test.txt
- setup.py
For some reason ever since using the syntax `>=` in setup.py #904 the file is no longer having the version of the drivers bumped in renovate PRs. 
Manually bumping for now.
Closes #951
> deps: update dependency pg8000 to v1.30.4

- google/cloud/sql/connector/connector.py
- tests/unit/test_connector.py
Attempting to make the `.close` of the Connector more useful and to attempt to close on garbage collection.
Garbage collection does not guarantee when something will be called. `.close()` needs to be able to be called twice in case someone explicitly closes and then garbage collection is performed.
> chore: improve connector.close

- google/cloud/sql/connector/connector.py
- google/cloud/sql/connector/exceptions.py
- google/cloud/sql/connector/instance.py
- google/cloud/sql/connector/utils.py
- tests/conftest.py
- tests/unit/test_connector.py
- tests/unit/test_instance.py
- tests/unit/test_utils.py
Refactor the `credentials` from being initialized at the `Instance` level to the `Connector` level.
Improvement already made as a new credentials object was being used for each `Instance`, now done once and shared across all instances.
Part of the work to move to using one client session per Connector #873
> chore: refactor credentials to be initialized in Connector

- google/cloud/sql/connector/refresh_utils.py
- setup.py
- tests/unit/mocks.py
- tests/unit/test_instance.py
- tests/unit/test_refresh_utils.py
Overall, datetime aware datetimes `datetime.now(timezone)` are recommended over datetime naive datetimes `datetime.utcnow()` etc and Python is beginning to slowly deprecate datetime naive as it leads to ambiguity overall. Switching over our repo to datetime aware.
Context: https://blog.miguelgrinberg.com/post/it-s-time-for-a-change-datetime-utcnow-is-now-deprecated
As well in cryptography library (v42.0.0) there is a new `not_valid_after_utc` datetime attribute that is datetime aware and is recommended over `not_valid_after` which is naive. A deprecation warning will be removed with this update.
Need to update `google.auth` credentials expiry to be timezone aware as [auth library strips the timezone info](https://github.com/googleapis/google-auth-library-python/blob/main/google/auth/_helpe …
> chore: update datetime objects to be datetime aware

- google/cloud/sql/connector/connector.py
- google/cloud/sql/connector/instance.py
- tests/conftest.py
- tests/unit/test_instance.py
Barrier to async functionality is through `connect.connect_async` at which point the `Instance()` is configured. At this stage in execution flow we are already running with the given event loop so it is redundant  to pass it to  Instance and instead we should follow best practice and purely use  higher level `asyncio.create_task` which is recommended.
> refactor: remove loop argument from Instance

- google/cloud/sql/connector/connector.py
Remove `__del__` destructor for Connector as it seems to be causing timeout errors that were introduced as part of #985 
Closes #1000
> chore: remove destructor

- README.md
- google/cloud/sql/connector/connector.py
- google/cloud/sql/connector/instance.py
- tests/system/test_pg8000_connection.py
- tests/system/test_pymysql_connection.py
- tests/system/test_pytds_connection.py
- tests/unit/test_connector.py
Adding support for `ip_type` as `str` type with options as `"public"`, `"private"` or `"psc"`.
If users want to configure a Connector for a specific IP type they currently need to import `IPTypes` first and then set `ip_type=IPTypes.PUBLIC` in the Connector config or during their call to connect.
```python
from google.cloud.sql.connector import IPTypes
```
This is an extra step that is unnecessary and causes friction to users, we should support users passing in the IPTypes enum or string value. This will allow users to not have to import the additional class.
> feat: support `ip_type` as str

- .flake8
- google/cloud/sql/connector/connector.py
- google/cloud/sql/connector/instance.py
- tests/unit/test_connector.py
Aligning approach as close as possible to https://github.com/GoogleCloudPlatform/alloydb-python-connector/pull/267
Using built-in `__missing__` to better raise custom error message: https://stackoverflow.com/questions/68899057/can-one-add-a-custom-error-in-enum-to-show-valid-values
> refactor: update IPTypes

- google/cloud/sql/connector/client.py
- google/cloud/sql/connector/connector.py
- tests/unit/test_client.py
For TPC support we need to differentiate between if a user has passed in `sqladmin_api_endpoint` vs if its being defaulted. 
To do this we will default to `None` and use a global default endpoint `"https://sqladmin.googleapis.com"` when the endpoint is not explicitly set. This will allow for checking if a user has passed in a custom endpoint or not to support TPC cases.
> refactor: update defaulting of service endpoint

- google/cloud/sql/connector/connector.py
Google has it's own Python style guide which covers docstrings: https://google.github.io/styleguide/pyguide.html#38-comments-and-docstrings
The Python Connector currently does not follow this style guide for docstrings. This PR is the first of several that will move the library over to Google style docstrings.
Related to #1018
> refactor: use Google style docstrings for connector.py

- google/cloud/sql/connector/client.py
If custom user agent is not of type `str`, do not use it and use default user agent.
> chore: verify custom user agent is type str

- google/cloud/sql/connector/connector.py
- google/cloud/sql/connector/instance.py
- tests/conftest.py
- tests/system/test_connector_object.py
- tests/unit/test_connector.py
- tests/unit/test_instance.py
Rename `Instance` to `RefreshAheadCache` to get ready for adding a `LazyRefresh` type in the future. This will improve naming so customers are not confused by `Instance` not reflecting a Cloud SQL instance and instead being a cache of connection info to connect to a Cloud SQL instance.
Also updated `RefreshAheadCache` docstrings to match [Google style docstrings](https://google.github.io/styleguide/pyguide.html#38-comments-and-docstrings).
> refactor: rename Instance to RefreshAheadCache

- requirements-test.txt
For SQLAlchemy async engines (asyncpg usage) there are extra dependencies to install. 
Most platforms will come with the `greenlet` package pre-installed but macOS does not, Github has stopped pre-installing on their hosted runners. To guarantee the deps are installed we can use `sqlalchemy[asyncio]`
Ref: https://docs.sqlalchemy.org/en/20/orm/extensions/asyncio.html#asyncio-platform-installation-notes-including-apple-m1
Fixes #1071 
Fixes #1072
> chore: update SQLAlchemy dep to include optional asyncio deps

- google/cloud/sql/connector/connector.py
- google/cloud/sql/connector/exceptions.py
- google/cloud/sql/connector/instance.py
- tests/conftest.py
- tests/unit/mocks.py
- tests/unit/test_instance.py
- tests/unit/test_refresh_utils.py
This refactor moves all SSL/TLS configuration into its own method `create_ssl_context()` on the `ConnectionInfo` class.
This way `ConnectionInfo()` prepares all the info required to connect and then `create_ssl_context` will use the info to establish the SSL/TLS connection when called from `Connector.connect` at the time of connection.
This refactor also improves the testing infra to be more in line with AlloyDB Python Connector.
Based on Go: https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/pull/761
> refactor: move SSL/TLS context creation to ConnectionInfo

- README.md
Add use of rendered notices in README.
Also updating SQL Server verbiage slightly
> chore: use rendered notices in README

- google/cloud/sql/connector/client.py
- google/cloud/sql/connector/instance.py
- tests/unit/mocks.py
- tests/unit/test_refresh_utils.py
In the google.auth package, it is now recommended to use `.token_state`
over `.valid` for checking validity of credentials.
Token state gives more information such as if token is stale, expired,
invalid etc.
`.valid` is now marked as deprecated ([code](https://github.com/googleapis/google-auth-library-python/blob/main/google/auth/credentials.py#L87C5-L97C59)):
```python
@property
def valid(self):
"""Checks the validity of the credentials.
This is True if the credentials have a :attr:`token` and the token
is not :attr:`expired`.
.. deprecated:: v2.24.0
Prefer checking :attr:`token_state` instead.
"""
return self.token is not None and not self.expired
```
Closes #1048
> refactor: use google.auth TokenState for credentials validity

- google/cloud/sql/connector/client.py
- google/cloud/sql/connector/connection_info.py
- google/cloud/sql/connector/instance.py
- tests/unit/test_instance.py
Refactor revolving around `ConnectionInfo` in preparation for adding a
`LazyRefreshCache`.
Moving `ConnectionInfo` into its own file, `connection_info.py` as it is
to be shared by both `RefreshAheadCache` and `LazyRefreshCache`.
Adding a `get_connection_info` method to the `CloudSQLClient`.
This is the equivalent of the Go Connector's [refresher.ConnectInfo](https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/blob/4b68de3693e25642acd847d0c8ac393982d00c9b/internal/cloudsql/refresh.go#L274).
This will allow the lazy refresh to just check expiration and then call
`get_connection_info` and not need to duplicate code from refresh
ahead cache.
Related to #805
> refactor: move ConnectionInfo to own file and add `get_connection_info`

- google/cloud/sql/connector/connector.py
- google/cloud/sql/connector/instance.py
- tests/unit/test_instance.py
Remove `ip_type` from `RefreshAheadCache.connect_info()`.
The `connect_info` method should return the `ConnectionInfo`
for the given cache and that is all. 
Currently, it gets the connection info, then gets the ip address of 
the connection info and returns both. This is just not necessary as
the ConnectionInfo already contains the method to get the
preferred IP address so we should return the `ConnectionInfo` as
is and have the `Connector.connect` grab the preferred IP for a
more straightforward flow.
This matches the Go Connectors use of [`ConnectionInfo.Addr`](https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/blob/main/internal/cloudsql/instance.go#L200)
> refactor: remove `ip_type` from connect_info

- README.md
- google/cloud/sql/connector/__init__.py
- google/cloud/sql/connector/connector.py
- google/cloud/sql/connector/instance.py
- google/cloud/sql/connector/lazy.py
- tests/system/test_pg8000_iam_auth.py
- tests/unit/test_lazy.py
Add `refresh_strategy` argument to `Connector()` that allows setting
the strategy to `"lazy"` to use a lazy refresh strategy.
When creating a Connector via `Connector(refresh_strategy="lazy")`,
the connection info and ephemeral certificate will be refreshed only
when the cache certificate has expired. No background tasks run
periodically with this option, making it ideal for use in serverless
environments such as Cloud Run, Cloud Functions, etc, where the
CPU may be throttled.
Usage example:
```python
from google.cloud.sql.connector import Connector
with Connector(refresh_strategy="lazy") as connector:
```
> feat: add support for lazy refresh strategy

- README.md
- google/cloud/sql/connector/client.py
- google/cloud/sql/connector/connector.py
- google/cloud/sql/connector/instance.py
Standardize optional debug logging across Cloud SQL Connector packages.
To print debug logs for the Python Connector package add the following to your application:
```python
import logging
logging.basicConfig(format="%(asctime)s [%(levelname)s]: %(message)s")
logger = logging.getLogger(name="google.cloud.sql.connector")
logger.setLevel(logging.DEBUG)
```
Example of the debug logs produced:
```sh
2024-05-31 18:27:30,472 [DEBUG]: ['my-project:my-region:my-instance']: Refresh strategy is set to backgound refresh
2024-05-31 18:27:30,473 [DEBUG]: ['my-project:my-region:my-instance']: Connection info added to cache
2024-05-31 18:27:30,473 [DEBUG]: ['my-project:my-region:my-instance']: Connection info refresh operation started
2024-05-31 18:27:30,771 [DEBUG]: …
```
> feat: add standardized debug logging

- google/cloud/sql/connector/connector.py
- google/cloud/sql/connector/enums.py
- google/cloud/sql/connector/exceptions.py
- tests/unit/test_connector.py
Removing ambiguous behavior if a user configures a database
driver to connect to an incompatible database engine.
i.e. `pymysql` (MySQL driver) -> Cloud SQL for PostgreSQL database
This behavior would timeout trying to connect and then throw
an ambiguous timeout error.
The `Connector.connect` already know which database engine
the Cloud SQL database is prior to attempting to connect via the
driver. So we can validate if the driver is compatible and throw an
actionable error if not.
Closes #998
> feat: validate driver with database engine

- google/cloud/sql/connector/__init__.py
- google/cloud/sql/connector/connection_info.py
- google/cloud/sql/connector/connector.py
- google/cloud/sql/connector/enums.py
- google/cloud/sql/connector/instance.py
- tests/unit/test_instance.py
Moving enum types to file`enums.py`.
`IPTypes` and `RefreshStrategy` are shared and as such should
not be in `instance.py` as it holds mostly RefreshAheadCache code.
> refactor: move all enums to enum.py

- google/cloud/sql/connector/connector.py
- tests/unit/test_connector.py
RSA key-pair generation should be done on first connection
attempt when lazy refresh strategy is configured.
> chore: lazy init keys with lazy refresh

- google/cloud/sql/connector/connection_info.py
- google/cloud/sql/connector/connector.py
- tests/unit/test_connector.py
The `Connector` caches connection info for future connections and
schedules refresh operations, however for unrecoverable errors/state
we should invalidate the cache to stop future bad refreshes.
We should invalidate the cache on all failed calls to the Cloud SQL Admin
APIs, as well as failed IP lookup (preferred IP does not exist).
Added a `._remove_cached` method to the Connector to facilitate 
invalidating the cache.
Closes #1098
> feat: invalidate cache on bad connection info and IP lookup

- google/cloud/sql/connector/client.py
- google/cloud/sql/connector/connector.py
- google/cloud/sql/connector/exceptions.py
Python's `SSLContext` requires trailing dot to be stripped from DNS
names in order to properly configure SSL/TLS.
Previously, we were resolving the DNS and connecting to the PSC
endpoint within the Connector. However, this was a poor workaround
as we should really just strip the trailing dot and allow the drivers to
resolve the DNS on connection.
> fix: let DNS resolve outside connector

- google/cloud/sql/connector/client.py
- google/cloud/sql/connector/refresh_utils.py
- tests/unit/test_refresh_utils.py
This commit adds retry behavior to the two SQL Admin API calls. 
Any response that results in a 50x error will now be retried up to
5 times with exponential backoff and jitter between each attempt.
The formula used to calculate the duration to wait is:
200ms * 1.618^(attempt + jitter)
This calculation matches what the Cloud SQL Proxy v1 did and
will not trigger any significant change in load on the backend.
> fix: retry 50x errors with exponential backoff

- .github/workflows/tests.yml
Until Github env variables can be accessed via PRs from forks, they are
unusable for our repos since we leverage renovate bot for our dependency PRs.
Ref: https://github.com/orgs/community/discussions/44322
> chore: update use of Github env variables

- .github/workflows/tests.yml
Reverts GoogleCloudPlatform/cloud-sql-python-connector#1135
Google Auth Github Action requires `id-token` with `write` access
yet forks have a max permission of `read` on the `id-token` ([source](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token))
> chore: revert changes to env var usage

- .github/workflows/tests.yml
Google Auth Github action can not run on fork PRs as `id-token` is scoped to read only.
To unblock renovate bot PRs and external PRs we will skip integration tests for the time being from forks.
> chore: skip integration tests on forks

- .github/workflows/tests.yml
Pull request from forks once merged will still be skipped `github.event.pull_request.head.repo.full_name` will still be that of the fork.
To combat this we run the job on all events that are not a pull_request (aka `schedule` and `push`)
> ci: update integration test logic

- google/cloud/sql/connector/connection_info.py
- google/cloud/sql/connector/connector.py
- google/cloud/sql/connector/utils.py
- requirements.txt
- setup.py
- tests/unit/mocks.py
- tests/unit/test_instance.py
Currently we use Python's standard library read and writes which are blocking.
This PR switches to use [aiofiles](https://pypi.org/project/aiofiles/) which is asyncio native approach to
read/write to disk.
Closes #1141
> feat: use non-blocking disk read/writes

- tests/system/test_asyncpg_connection.py
- tests/system/test_asyncpg_iam_auth.py
- tests/system/test_pg8000_connection.py
- tests/system/test_pg8000_iam_auth.py
- tests/system/test_pymysql_connection.py
- tests/system/test_pymysql_iam_auth.py
- tests/system/test_pytds_connection.py
Current integration tests use a bad practice of initializing the `Connector`
within the `getconn` creator func. This creates a `Connector` on each
database conn instead of re-using a single connector:
```python
def getconn() -> pg8000.dbapi.Connection:
with Connector() as connector:
```
This PR also makes a single test file be able to have tests connect to
different Cloud SQL instances (wanted for CAS tests) by removing
the pytest fixture in place of helper func.
> test: update tests to be more scalable

- .github/workflows/tests.yml
- tests/system/test_pg8000_connection.py
Add integration test to a CAS-based CAs instance.
Because [hostname verification is currently disabled](https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/blob/610209d246974e89820534e6f151b879f72d4b29/google/cloud/sql/connector/connection_info.py#L60-L61) we do not 
need any changes to the lib to support CAS-based instances.
When hostname verification is enabled in the lib via #1087
we will need to add additional logic to handle CAS-instances.
> test: add CAS-based CAs instance to test

- google/cloud/sql/connector/client.py
- tests/unit/mocks.py
- tests/unit/test_client.py
With CAS-based instances being supported soon and also using `dnsName`, 
we can no longer rely on the presence of `dnsName` in the connectSettings
API as identifying that PSC is enabled on an instance. 
Instead we should check `pscEnabled` from the response as source of truth.
Check if `pscEnabled` is `True` before setting PSC ip type.
> fix: set PSC ip type based on `pscEnabled`

- google/cloud/sql/connector/connector.py
- tests/system/test_connector_object.py
- tests/unit/test_connector.py
Improve dictionary key for `connector._cache`.
Previously, key for dictionary was the Cloud SQL instance's connection name
(`instance_connection_string`). 
```python
cache = connector._cache[instance_connection_string]
```
However, there is differing logic for connecting with `enable_iam_auth=True`
vs without. This resulted in having to throw an error and having a customer
create two separate connector objects if they want to connect to a single
instance with both auto IAM AuthN and regular user/password.
This PR makes the dictionary key a tuple consisting of `(instance_connection_string, enable_iam_auth)`.
This allows a single connector to cache two separate entries for the same Cloud SQL instance,
one for `enable_iam_auth=True` and one for `enable_iam_auth=False`.
```python
cache = …
```
> feat: improve key for connector cache

- .kokoro/release.sh
- .kokoro/release/common.cfg
The pypi publication keystore key has been rotated yet again.
> chore: update pypi publication keystore version

- .github/workflows/tests.yml
- noxfile.py
- setup.py
Python 3.13 is now a stable release and GA.
Add it to supported versions in `setup.py` and test suite.
[Released on October 7, 2024](https://www.python.org/downloads/release/python-3130/)
Closes #1178
> feat: add support for Python 3.13

- README.md
- setup.py
- tests/system/test_asyncpg_connection.py
As of [`asyncpg v0.30.0`](https://github.com/MagicStack/asyncpg/releases/tag/v0.30.0), asyncpg native connection pools now support
a creation function (callable) via its `connect` argument, similar to
SQLAlchemy's `async_creator` argument to generate connections.
Adding integration test and usage samples to README.
Also bumping asyncpg min supported version in `setup.py` to `0.30.0`
to force supported version for this feature. 
Closes #1180
> feat: support native asyncpg connection pools

- google/cloud/sql/connector/asyncpg.py
- google/cloud/sql/connector/client.py
- google/cloud/sql/connector/connection_info.py
- google/cloud/sql/connector/connector.py
- google/cloud/sql/connector/instance.py
- google/cloud/sql/connector/refresh_utils.py
- google/cloud/sql/connector/utils.py
- tests/system/test_asyncpg_connection.py
- tests/system/test_asyncpg_iam_auth.py
- tests/system/test_ip_types.py
- tests/system/test_pg8000_connection.py
- tests/system/test_pg8000_iam_auth.py
- tests/system/test_pymysql_connection.py
- tests/system/test_pymysql_iam_auth.py
- tests/system/test_pytds_connection.py
- tests/unit/mocks.py
- tests/unit/test_asyncpg.py
Updates type hints to use standard collections (`list`, `tuple`, `dict`). 
We can do this now that Python 3.8 was removed
As of Python 3.9 and [PEP 585](https://peps.python.org/pep-0585/) standard collections can be subscripted in
favor of their `typing` counterparts which are now deprecated.
> chore: update type hints to standard collections

- google/cloud/sql/connector/connection_name.py
- google/cloud/sql/connector/instance.py
- google/cloud/sql/connector/lazy.py
- google/cloud/sql/connector/pg8000.py
- google/cloud/sql/connector/pymysql.py
- google/cloud/sql/connector/pytds.py
- noxfile.py
- tests/conftest.py
- tests/unit/test_connection_name.py
- tests/unit/test_instance.py
- tests/unit/test_pg8000.py
- tests/unit/test_pymysql.py
- tests/unit/test_pytds.py
- tests/unit/test_rate_limiter.py
- tests/unit/test_utils.py
This PR refactors all instance connection name related code into
its own file `connection_name.py`.
It introduces the `ConnectionName` class which will make tracking
if a DNS name was given to the Connector easier in the future.
This change also aligns the Python Connector more closely to its
Go counterpart's [`conn_name.go`](https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/blob/b228ed7c737467f29b99fff8074bc754b3ce2e81/instance/conn_name.go) for easier maintainability.
Related to #1169
> refactor: add `ConnectionName` class

- tests/unit/test_refresh_utils.py
We have seen the backoff value be microseconds below the low value causing test failures.
```
FAILED tests/unit/test_refresh_utils.py::test_exponential_backoff[0-324-524] - assert 323.97999248703616 >= 324
```
Rounding the answer to the nearest millisecond value will reduce flaky test.
Closes https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/issues/1160
> test: round backoff in exponential backoff tests

- google/cloud/sql/connector/client.py
- google/cloud/sql/connector/instance.py
- tests/unit/test_client.py
- tests/unit/test_instance.py
By default, `aiohttp` on bad requests will discard response body and
output generic error message in response, `Bad Request`, `Forbidden`, etc.
The Cloud SQL Admin APIs response body contains more detailed error messages.
We need to raise these to the end user for them to be able to resolve common config 
issues on their own.
In https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/pull/362 we caught `403` errors and implemented a custom error message
to point users at the most common config issues, Cloud SQL API not being enabled,
missing `Cloud SQL Client` role etc. However, this was not a catch-all (as noted by #1199) 
and more of a temporary fix.
This PR implements a more robust solution, copying the actual Cloud SQL Admin API
response body's error message to the end user. …
> feat: improve aiohttp client error messages

- google/cloud/sql/connector/connection_name.py
- google/cloud/sql/connector/resolver.py
- tests/unit/test_connection_name.py
Add `domain_name` to `ConnectionName` dataclass.
PR also updates `_parse_connection_name` to wrap new
`_parse_connection_name_with_domain_name` to account for
domain name.
Part of #1169
> refactor: add `domain_name` to `ConnectionName` class

- noxfile.py
- tests/unit/test_connection_name.py
We use both `isort` and `black` formatter's as part of our lint job.
`isort` has [preset profiles](https://pycqa.github.io/isort/docs/configuration/profiles.html), we were using `google` previously but it has begun to
cause conflicts with the black formatter, leading to lint job failures.
Instead, we can use the `black` profile for isort and then manually toggle the other
flags to match the `google` profile.
> ci: use black isort profile and update to latest

- google/cloud/sql/connector/client.py
- google/cloud/sql/connector/connection_info.py
- google/cloud/sql/connector/connector.py
- google/cloud/sql/connector/instance.py
- google/cloud/sql/connector/lazy.py
- google/cloud/sql/connector/resolver.py
- tests/unit/test_connection_name.py
- tests/unit/test_instance.py
- tests/unit/test_resolver.py
Adding `ConnectionName` to `ConnectionInfo` class to more closely match [Go implementation](https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/blob/5061c61092c3fa92175ca8502a365e6e82993b6e/internal/cloudsql/instance.go#L175).
Benefits:
- Cleaner interface, passing connection name around instead of individual args (project, region, instance)
- Consistent debug logs (give access to ConnectionName throughout)
- Allows us to tell if ConnectionInfo is using DNS  (if `ConnectionName.domain_name` is set)
This will unblock DNS polling as we must know at the `ConnectionInfo` level if it is
configured via DNS domain name or not.
Related to #1169
> refactor: add `ConnectionName` to `ConnectionInfo` class

- google/cloud/sql/connector/enums.py
Lint job is complaining:
```
google/cloud/sql/connector/enums.py:23: error: Enum members must be left unannotated  [misc]
```
Enums should not be type hinted.
Since our Enums are of type `str` we should be using [`enum.StrEnum`](https://docs.python.org/3/library/enum.html#enum.StrEnum)
but it was only added in Python 3.11. Added a `TODO` for the future.
> chore: remove type annotations for Enums

- google/cloud/sql/connector/connector.py
Looks like we missed `Type` as part of https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/pull/1183
Standard collection `type` can now be used over `Type`
Mentioned in [PEP585](https://peps.python.org/pep-0585/#implementation)
> chore: replace usage of `Type` with `type` standard collection

- google/cloud/sql/connector/connector.py
- tests/unit/test_connector.py
Add support for `universe_domain` to be set via the `GOOGLE_CLOUD_UNIVERSE_DOMAIN` env var.
This will allow zero code changes to support non-GDU environments, instead users can set the env var.
Order of operations for setting universe domain will be as follows:
1. Use `universe_domain` argument passed to `Connector()`
2. Use `GOOGLE_CLOUD_UNIVERSE_DOMAIN` env var
3. Use default `"googleapis.com"`
Fixes #1217
> feat: add support for `GOOGLE_CLOUD_UNIVERSE_DOMAIN` env var

- google/cloud/sql/connector/connector.py
- tests/unit/test_connector.py
Add support for `quota_project` to be set via the `GOOGLE_CLOUD_QUOTA_PROJECT` env var.
Order of operations for setting quota project will be as follows:
1. Use `quota_project` argument passed to `Connector()`
2. Use `GOOGLE_CLOUD_QUOTA_PROJECT` env var
3. Set default to `None` (project set in environment)
Fixes #1229
> feat: add support for `GOOGLE_CLOUD_QUOTA_PROJECT` env var

- .kokoro/release.sh
In #1230 we moved package off of `setup.py` and over to `pyproject.toml`
Forgot a spot to update in `release.sh` which references `setup.py` which no longer exists.
Related to #1230
> build: update release.sh to not use setup.py

- .gitignore
- google/cloud/sql/connector/client.py
- tests/unit/mocks.py
- tests/unit/test_client.py
When the connector is configured with a DNS name, or if the Cloud SQL Instance reports that it has a DNS Name,
the connector will use standard TLS hostname validation when checking the server certificate. Now, the server's
TLS certificate must contain a SAN record with the instance's DNS name.
The ConnectSettings API added a field dns_names which contains all of the valid DNS names for
an instance.
See also: https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/pull/954
> refactor: Use new ConnectSettings.DnsNames field to validate the server TLS certificate. 

- pyproject.toml
Fixing lint warnings as license classifiers are deprecated and removing use of [legacy-license-declaration](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#legacy-license-declaration)
```
/tmp/build-env-ln2q3kq1/lib/python3.12/site-packages/setuptools/config/_apply_pyprojecttoml.py:82: SetuptoolsDeprecationWarning: `project.license` as a TOML table is deprecated
!!
********************************************************************************
Please use a simple string containing a SPDX expression for `project.license`. You can also use `project.license-files`.
By 2026-Feb-18, you need to update your project and remove deprecated calls
or your builds will no longer be supported.
See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for …
```
> build: update license identifiers in pyproject.toml

- README.md
- tests/system/test_asyncpg_connection.py
- tests/system/test_asyncpg_iam_auth.py
- tests/system/test_pg8000_connection.py
- tests/system/test_pg8000_iam_auth.py
- tests/system/test_pymysql_connection.py
- tests/system/test_pymysql_iam_auth.py
- tests/system/test_pytds_connection.py
Update README and integration tests to be more pythonic by using `lambda`
over intermediate `getconn` function.
Reduces code required and is more readable.
Instead of using `getconn`:
```python
def getconn() -> pymysql.connections.Connection:
conn: pymysql.connections.Connection = connector.connect(
"project:region:instance",
"pymysql",
user="my-user",
password="my-password",
db="my-db-name"
)
return conn
pool = sqlalchemy.create_engine(
"mysql+pymysql://",
creator=getconn,
)
```
We can simplify it using a `lambda`:
```python
pool = sqlalchemy.create_engine(
"mysql+pymysql://",
creator=lambda: connector.connect(
"project:region:instance",
"pymysql",
user="my-user",
password="my-password",
db="my-db-name"
),
)
```
> docs: use lambda over getconn func

- google/cloud/sql/connector/asyncpg.py
- google/cloud/sql/connector/client.py
- google/cloud/sql/connector/pg8000.py
- google/cloud/sql/connector/pymysql.py
- google/cloud/sql/connector/pytds.py
- google/cloud/sql/connector/rate_limiter.py
- google/cloud/sql/connector/refresh_utils.py
- google/cloud/sql/connector/utils.py
This PR is intended to continue refactoring the Python Connector library over to Google style docstrings.
Related to [#1018](https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/issues/1018)
> refactor: update to Google style docstrings

- tests/system/test_connector_object.py
Removing test_connector_with_credentials from tests/system/test_connector_object.py as unit tests already cover the credential tests
Reference bug: b/396351603
> test: remove test_connector_with_credentials system test

- tests/system/test_asyncpg_connection.py
- tests/system/test_asyncpg_iam_auth.py
- tests/system/test_connector_object.py
- tests/system/test_ip_types.py
- tests/system/test_pg8000_connection.py
- tests/system/test_pg8000_iam_auth.py
- tests/system/test_pymysql_connection.py
- tests/system/test_pymysql_iam_auth.py
- tests/system/test_pytds_connection.py
Updates ip_type parameter to use environment variable - "IP_TYPE" to enable private IP tests. The default still remains "public"
Reference: b/396351603
> test: update ip type for connectors

- tests/conftest.py
- tests/unit/mocks.py
- tests/unit/test_instance.py
- tests/unit/test_monitored_cache.py
- tests/unit/test_pg8000.py
- tests/unit/test_pymysql.py
- tests/unit/test_pytds.py
This PR improves the local server used for unit tests.
The previous `server` fixture was just a plain socket unable to perform SSL/TLS.
This meant in certain tests we were skipping the SSL/TLS handshake because it
would fail. 
The new `proxy_server` fixture more closely behaves to that of the real Proxy server.
It allows SSL/TLS by loading in the server CA used for testing, the client can then
use the new  `context` fixture to properly use SSL to connect to the server.
This will provide a foundation for testing the metadata exchange which will be
introduced in the near future.
> test: update server used for tests to use SSL/TLS

- .github/workflows/coverage.yml
Code coverage check is failing due to not finding a Python 3.10 distribution.
We are using Python 3.13 in the setup-python section of the coverage job but
then running nox with Python 3.10.
https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/blob/27f6de3268605fe9d03913ba351bb754c0c9ff5c/.github/workflows/coverage.yml#L29-L40
Both setup-python and nox should run using same Python version
> chore: update code coverage to use proper python version

- .gitignore
- build.sh
- google/cloud/sql/connector/client.py
- google/cloud/sql/connector/connector.py
- google/cloud/sql/connector/refresh_utils.py
- noxfile.py
- tests/unit/mocks.py
- tests/unit/test_client.py
- tests/unit/test_connector.py
- tests/unit/test_refresh_utils.py
Adds the a standardized developer commands script "build.sh" that will exist in this and all other Cloud SQL Connector projects.
https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/pull/2122
> chore: Add build.sh common build script.
